<?php
/**
 * V 1.0
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ThemeOptions {
    private $theme_options_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'theme_options_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'theme_options_page_init' ) );
    }

    public function theme_options_add_plugin_page() {
        add_menu_page(
            'Theme options', // page_title
            'Theme options', // menu_title
            'manage_options', // capability
            'theme-options', // menu_slug
            array( $this, 'theme_options_create_admin_page' ), // function
            'dashicons-media-code', // icon_url
            100 // position
        );
    }

    public function theme_options_create_admin_page() {
        $this->theme_options_options = get_option( 'theme_options_option_name' ); ?>

        <div class="wrap">
            <h2>Theme options</h2>
            <p></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields( 'theme_options_option_group' );
                do_settings_sections( 'theme-options-admin' );
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function theme_options_page_init() {
        register_setting(
            'theme_options_option_group', // option_group
            'theme_options_option_name', // option_name
            array( $this, 'theme_options_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'theme_options_setting_section', // id
            'Settings', // title
            array( $this, 'theme_options_section_info' ), // callback
            'theme-options-admin' // page
        );

        add_settings_field(
            'phone_number_one_0', // id
            'Phone number one', // title
            array( $this, 'phone_number_one_0_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'phone_number_two_1', // id
            'Phone number two', // title
            array( $this, 'phone_number_two_1_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'phone_number_three_2', // id
            'Phone number three', // title
            array( $this, 'phone_number_three_2_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'email_address_3', // id
            'Email address', // title
            array( $this, 'email_address_3_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'address_4', // id
            'Address', // title
            array( $this, 'address_4_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'front_heading_5', // id
            'Front heading', // title
            array( $this, 'front_heading_5_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'front_subheading_6', // id
            'Front subheading', // title
            array( $this, 'front_subheading_6_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'seo_heading_7', // id
            'Seo heading', // title
            array( $this, 'seo_heading_7_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );

        add_settings_field(
            'seo_content_8', // id
            'Seo content', // title
            array( $this, 'seo_content_8_callback' ), // callback
            'theme-options-admin', // page
            'theme_options_setting_section' // section
        );
    }

    public function theme_options_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['phone_number_one_0'] ) ) {
            $sanitary_values['phone_number_one_0'] = sanitize_text_field( $input['phone_number_one_0'] );
        }

        if ( isset( $input['phone_number_two_1'] ) ) {
            $sanitary_values['phone_number_two_1'] = sanitize_text_field( $input['phone_number_two_1'] );
        }

        if ( isset( $input['phone_number_three_2'] ) ) {
            $sanitary_values['phone_number_three_2'] = sanitize_text_field( $input['phone_number_three_2'] );
        }

        if ( isset( $input['email_address_3'] ) ) {
            $sanitary_values['email_address_3'] = sanitize_text_field( $input['email_address_3'] );
        }

        if ( isset( $input['address_4'] ) ) {
            $sanitary_values['address_4'] = sanitize_text_field( $input['address_4'] );
        }

        if ( isset( $input['front_heading_5'] ) ) {
            $sanitary_values['front_heading_5'] = sanitize_text_field( $input['front_heading_5'] );
        }

        if ( isset( $input['front_subheading_6'] ) ) {
            $sanitary_values['front_subheading_6'] = sanitize_text_field( $input['front_subheading_6'] );
        }

        if ( isset( $input['seo_heading_7'] ) ) {
            $sanitary_values['seo_heading_7'] = sanitize_text_field( $input['seo_heading_7'] );
        }

        if ( isset( $input['seo_content_8'] ) ) {
            $sanitary_values['seo_content_8'] = esc_textarea( $input['seo_content_8'] );
        }

        return $sanitary_values;
    }

    public function theme_options_section_info() {

    }

    public function phone_number_one_0_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[phone_number_one_0]" id="phone_number_one_0" value="%s">',
            isset( $this->theme_options_options['phone_number_one_0'] ) ? esc_attr( $this->theme_options_options['phone_number_one_0']) : ''
        );
    }

    public function phone_number_two_1_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[phone_number_two_1]" id="phone_number_two_1" value="%s">',
            isset( $this->theme_options_options['phone_number_two_1'] ) ? esc_attr( $this->theme_options_options['phone_number_two_1']) : ''
        );
    }

    public function phone_number_three_2_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[phone_number_three_2]" id="phone_number_three_2" value="%s">',
            isset( $this->theme_options_options['phone_number_three_2'] ) ? esc_attr( $this->theme_options_options['phone_number_three_2']) : ''
        );
    }

    public function email_address_3_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[email_address_3]" id="email_address_3" value="%s">',
            isset( $this->theme_options_options['email_address_3'] ) ? esc_attr( $this->theme_options_options['email_address_3']) : ''
        );
    }

    public function address_4_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[address_4]" id="address_4" value="%s">',
            isset( $this->theme_options_options['address_4'] ) ? esc_attr( $this->theme_options_options['address_4']) : ''
        );
    }

    public function front_heading_5_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[front_heading_5]" id="front_heading_5" value="%s">',
            isset( $this->theme_options_options['front_heading_5'] ) ? esc_attr( $this->theme_options_options['front_heading_5']) : ''
        );
    }

    public function front_subheading_6_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[front_subheading_6]" id="front_subheading_6" value="%s">',
            isset( $this->theme_options_options['front_subheading_6'] ) ? esc_attr( $this->theme_options_options['front_subheading_6']) : ''
        );
    }

    public function seo_heading_7_callback() {
        printf(
            '<input class="regular-text" type="text" name="theme_options_option_name[seo_heading_7]" id="seo_heading_7" value="%s">',
            isset( $this->theme_options_options['seo_heading_7'] ) ? esc_attr( $this->theme_options_options['seo_heading_7']) : ''
        );
    }

    public function seo_content_8_callback() {
        printf(
            '<textarea class="large-text" rows="5" name="theme_options_option_name[seo_content_8]" id="seo_content_8">%s</textarea>',
            isset( $this->theme_options_options['seo_content_8'] ) ? esc_attr( $this->theme_options_options['seo_content_8']) : ''
        );
    }

}
if ( is_admin() )
    $theme_options = new ThemeOptions();

/*
 * Retrieve this value with:
 * $theme_options_options = get_option( 'theme_options_option_name' ); // Array of All Options
 * $phone_number_one_0 = $theme_options_options['phone_number_one_0']; // Phone number one
 * $phone_number_two_1 = $theme_options_options['phone_number_two_1']; // Phone number two
 * $phone_number_three_2 = $theme_options_options['phone_number_three_2']; // Phone number three
 * $email_address_3 = $theme_options_options['email_address_3']; // Email address
 * $address_4 = $theme_options_options['address_4']; // Address
 * $front_heading_5 = $theme_options_options['front_heading_5']; // Front heading
 * $front_subheading_6 = $theme_options_options['front_subheading_6']; // Front subheading
 * $seo_heading_7 = $theme_options_options['seo_heading_7']; // Seo heading
 * $seo_content_8 = $theme_options_options['seo_content_8']; // Seo content
 */
